server:
  port: 8080
spring:
  application:
    name: Gateway
  datasource:
    url: jdbc:mysql://localhost:3306/commerce?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345
  cloud:
    nacos:
      server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8084  # Sentinel Dashboard的地址
        port: 8719                 # 应用与Dashboard通信端口（默认为8719，无需更改）
      eager: true
      datasource:
        dsl:
         nacos:
          server-addr: 127.0.0.1:8848
          data-id: example-data-id
          group-id: DEFAULT_GROUP
          namespace: public
          rule-type: "flow"
    gateway:
      routes:
        - id: UserService
          uri: lb://UserService
          predicates:
            - Path=/user/**
        - id: ProductService
          uri: lb://ProductService
          predicates:
            - Path=/product/**
        - id: SeckillService
          uri: lb://SeckillService
          predicates:
            - Path=/order/**
lh:
  auth:
   excludePaths:
      - /user/login
      - /user/register