server:
  port: 8083
spring:
  application:
    name: SeckillService
  datasource:
    url: jdbc:mysql://localhost:3306/commerce?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345
  data:
    redis:
      cluster:
        nodes:
            - 127.0.0.1:7001
            - 127.0.0.1:7002
            - 127.0.0.1:7003
            - 127.0.0.1:7004
            - 127.0.0.1:7005
            - 127.0.0.1:7006
      password: 123456
  rabbitmq:
      host: localhost  # RabbitMQ 服务的主机地址
      port: 5672       # 默认的 RabbitMQ 端口
      username: guest   # 用户名
      password: guest   # 密码