server:
  port: 8082
spring:
  application:
    name: ProductService
  datasource:
    url: jdbc:mysql://localhost:3306/commerce?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345
  data:
    redis:
      host: localhost
      port: 6379